sidebar_title: "Zong"
sidebar_subtitle: "人之所以能<br>，是相信能"

truncate_len: 60

rss: # atom.xml
archives: false

giscus: true

copyright_start: 2017
copyright_end: 2024

# Declare license on posts
post_copyright:
  enable: true
  license: CC BY-NC-SA 3.0
  license_url: https://creativecommons.org/licenses/by-nc-sa/3.0/
